### ISSUE TITLE
Not compatible w/ >=R 3.4.3

### ISSUE THREAD

**Issue by mkrakora22798** [AliciaSchep/ggmotif#2]
I've been trying to install this package for R 3.4.3 and newer, however the console tells me that the package is not compatible. 
Which version of R, did you make/use this for?

**Comment by AliciaSchep** [comment]
This isn't on CRAN - so if error from `install.packages` that would be why!

Try installing using `devtools::install_github`. I'll update the README to mention this...

**Comment by mkrakora22798** [comment]
ok. thank you!
